package Database.Cards;

public enum MonsterType {
    WARRIOR, WARRIOR_EFFECT, WARRIOR_RITUAL, INSECT_EFFECT, BEAST, BEAST_WARRIOR, BEAST_WARRIOR_EFFECT, FIEND,
    AQUA_EFFECT, AQUA_RITUAL, SEA_SERPENT, SPELLCASTER, SPELLCASTER_EFFECT, THUNDER, THUNDER_EFFECT, DRAGON,
    DRAGON_EFFECT, MACHINE, MACHINE_EFFECT, PYRO, ROCK, CYBERSE, CYBERSE_EFFECT, FAIRY_EFFECT;
}
